# **Análisis exploratorio**

## Librerías y carga del archivo

In [1]:
# Librerías
import pandas as pd

In [2]:
# Carga del conjunto de datos
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/VYPrOu0Vs3I0hKLLjiPGrA/survey-data-with-duplicate.csv")

## Exploración del conjunto de datos

### Exploración general

In [3]:
df.head(5)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [4]:
df.shape # Identificando número de filas y columnas

(65457, 114)

In [5]:
df.dtypes # Identificando tipos de datos

ResponseId               int64
MainBranch              object
Age                     object
Employment              object
RemoteWork              object
                        ...
JobSatPoints_11        float64
SurveyLength            object
SurveyEase              object
ConvertedCompYearly    float64
JobSat                 float64
Length: 114, dtype: object

In [6]:
df.duplicated(subset='ResponseId').sum()

np.int64(20)

In [7]:
df.isnull().sum().reset_index().sort_values(ascending=False, by=0).head(10)

                             index      0
75      AINextMuch less integrated  64309
74           AINextLess integrated  63102
72                 AINextNo change  52955
71      AINextMuch more integrated  52018
36                 EmbeddedAdmired  48718
35          EmbeddedWantToWorkWith  47851
34          EmbeddedHaveWorkedWith  43236
112            ConvertedCompYearly  42020
70   AIToolNot interested in Using  41040
73           AINextMore integrated  41026

### Exploración enfocada

In [8]:
colums_selected = ['ResponseId', 'Age', 'EdLevel', 'YearsCode', 'YearsCodePro', 'Country', 'CompTotal', 'LanguageHaveWorkedWith', 
                   'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DatabaseAdmired', 
                   'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PlatformAdmired', 'NEWCollabToolsHaveWorkedWith', 
                   'NEWCollabToolsWantToWorkWith', 'NEWCollabToolsAdmired', 'TechEndorse']
df_focus = df[colums_selected]
df_focus.head()

,ResponseId,Age,EdLevel,YearsCode,YearsCodePro,Country,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,TechEndorse
0,1,Under 18 years old,Primary/elementary school,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",20,17,United Kingdom of Great Britain and Northern I...,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,NaN
2,3,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",37,27,United Kingdom of Great Britain and Northern I...,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,Visual Studio,Visual Studio,Visual Studio,NaN
3,4,18-24 years old,Some college/university study without earning ...,4,NaN,Canada,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),NaN,NaN,NaN,NaN
4,5,18-24 years old,"Secondary school (e.g. American high school, G...",9,NaN,Norway,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,Vim,Vim,Vim,NaN

In [9]:
df_focus.dtypes

ResponseId                        int64
Age                              object
EdLevel                          object
YearsCode                        object
YearsCodePro                     object
Country                          object
CompTotal                       float64
LanguageHaveWorkedWith           object
LanguageWantToWorkWith           object
LanguageAdmired                  object
DatabaseHaveWorkedWith           object
DatabaseWantToWorkWith           object
DatabaseAdmired                  object
PlatformHaveWorkedWith           object
PlatformWantToWorkWith           object
PlatformAdmired                  object
NEWCollabToolsHaveWorkedWith     object
NEWCollabToolsWantToWorkWith     object
NEWCollabToolsAdmired            object
TechEndorse                      object
dtype: object

In [10]:
null_sum = pd.DataFrame(
    {
        'nulos': df_focus.isnull().sum(),
        'porcentaje': df_focus.isnull().mean() * 100
    }
).sort_values(by='porcentaje', ascending=False)
null_sum

                              nulos  porcentaje
PlatformAdmired               34069   52.047909
CompTotal                     31713   48.448600
PlatformWantToWorkWith        30914   47.227951
DatabaseAdmired               26887   41.075821
PlatformHaveWorkedWith        23079   35.258261
DatabaseWantToWorkWith        22886   34.963411
TechEndorse                   21782   33.276808
DatabaseHaveWorkedWith        15188   23.203019
NEWCollabToolsAdmired         14730   22.503323
LanguageAdmired               14569   22.257360
YearsCodePro                  13834   21.134485
NEWCollabToolsWantToWorkWith  13354   20.401179
LanguageWantToWorkWith         9688   14.800556
NEWCollabToolsHaveWorkedWith   7848   11.989550
Country                        6508    9.942405
LanguageHaveWorkedWith         5694    8.698840
YearsCode                      5570    8.509403
EdLevel                        4654    7.110011
ResponseId                        0    0.000000
Age                               0    0.000000

In [11]:
df_focus.duplicated().sum()

np.int64(20)

In [12]:
df_focus.duplicated(subset='ResponseId').sum()

np.int64(20)

In [13]:
df_focus['YearsCode'].unique()

array([nan, '20', '37', '4', '9', '10', '7', '1', '15', '30', '31', '6',
       '12', '22', '5', '36', '25', '44', '24', '18', '3', '8',
       'More than 50 years', '11', '29', '40', '39', '2', '42', '34',
       '19', '35', '16', '33', '13', '23', '14', '28', '17', '21', '43',
       '46', '26', '32', '41', '45', '27', '38', '50', '48', '47',
       'Less than 1 year', '49'], dtype=object)

In [14]:
df_focus['YearsCodePro'].sort_values(ascending=False)

25434    More than 50 years
1941     More than 50 years
40012    More than 50 years
46216    More than 50 years
36787    More than 50 years
                ...
65441                   NaN
65442                   NaN
65444                   NaN
65445                   NaN
65448                   NaN
Name: YearsCodePro, Length: 65457, dtype: object

'NEWCollabToolsHaveWorkedWith',
 'NEWCollabToolsWantToWorkWith',
 'NEWCollabToolsAdmired',
  'ToolsTechHaveWorkedWith',
 'ToolsTechWantToWorkWith',
 'ToolsTechAdmired'

In [15]:
df_focus['Country'].nunique()

185

In [16]:
df_focus['Age'].unique()

array(['Under 18 years old', '35-44 years old', '45-54 years old',
       '18-24 years old', '25-34 years old', '55-64 years old',
       'Prefer not to say', '65 years or older'], dtype=object)